export default {
  digitalClock: {
    parent: "system",
    color: "#FFFFFF",
    backgroundColor: "#55586A",
    width: "fit-content",
    padding: "6px 10px",
    borderRadius: "10px",
    fontFamily: "Helvetica Neue",
    fontWeight: "bold",
  },
  digitalClockInactive: {
    parent: "system",
    color: "#55586A",
    backgroundColor: "#FFFFFF",
    width: "fit-content",
    padding: "6px 10px",
    borderRadius: "10px",
    fontFamily: "Helvetica Neue",
    fontWeight: "bold",
  },
  digitalClockError: {
    parent: "system",
    color: "#FFFFFF",
    backgroundColor: "#FF0000",
    width: "fit-content",
    padding: "6px 10px",
    borderRadius: "10px",
    fontFamily: "Helvetica Neue",
    fontWeight: "bold",
  },
};
