export type CollectionNames =
  | "book"
  | "eco"
  | "challengebuttons"
  | "challenges"
  | "connections"
  | "games"
  | "i18n"
  | "instances"
  | "libraries"
  | "librarygames"
  | "log_records"
  | "logger_configuration"
  | "themes"
  | "users"
  /* tests */
  | "dynamicselectorreactivereadonlytest"
  | "reactivereadonlydaotest"
  | "readonlydaotest"
  | "readwritedaotest";
